sonar.organization=estepa08
sonar.projectKey=Estepa08_health-react

sonar.sources=client/src,server/src
sonar.tests=client/src,server/src
sonar.test.inclusions=**/__tests__/**
sonar.exclusions=**/__tests__/**,client/dist/**,client/coverage/**

sonar.javascript.lcov.reportPaths=client/coverage/lcov.info
